const WEEK_GOALS_KEY='study-planner-week-goals-v1',MONTH_GOALS_KEY='study-planner-month-goals-v1';
let weekGoals=readGoals(WEEK_GOALS_KEY),monthGoals=readGoals(MONTH_GOALS_KEY),weekMode='schedule',monthMode='calendar',monthCursor=new Date(),monthSelected=new Date(),pendingGoalLink=null;
function readGoals(key){try{let value=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(value)?value:[]}catch{return[]}}
function persistGoals(){localStorage.setItem(WEEK_GOALS_KEY,JSON.stringify(weekGoals));localStorage.setItem(MONTH_GOALS_KEY,JSON.stringify(monthGoals));renderGoalAreas()}
function weekKey(date){return iso(startOfWeek(date))}function monthKey(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`}function periodGoals(type,key){return (type==='week'?weekGoals:monthGoals).filter(goal=>goal.periodKey===key)}
function renderGoalAreas(){renderWeekGoals();renderMonth()}
function renderWeekGoals(){let key=weekKey(weekStart),goals=periodGoals('week',key),panel=$('#week-goals-panel'),summary=$('#week-goal-summary'),list=$('#week-goal-list');panel.classList.toggle('hidden',weekMode!=='goals');$('#week-summary').classList.toggle('hidden',weekMode!=='schedule');summary.textContent=progressText(goals);renderGoalList(list,goals,'week')}
function progressText(goals){let done=goals.filter(goal=>goal.done).length;return goals.length?`${done} / ${goals.length}개 완료 · ${Math.round(done/goals.length*100)}%`:'아직 등록한 목표가 없어요. 작은 목표부터 추가해 보세요.'}
function renderGoalList(list,goals,type){list.innerHTML='';if(!goals.length){let empty=document.createElement('div');empty.className='empty';empty.textContent='이 기간의 목표가 없어요.';list.append(empty);return}goals.forEach(goal=>{let card=document.createElement('article');card.className='goal-card'+(goal.done?' done':'');let check=document.createElement('input');check.type='checkbox';check.checked=!!goal.done;check.setAttribute('aria-label',`${goal.title} 완료`);check.onchange=()=>{goal.done=check.checked;persistGoals()};let body=document.createElement('div'),title=document.createElement('h3'),meta=document.createElement('p'),actions=document.createElement('div');title.textContent=`${goal.subject} · ${goal.title}`;meta.textContent=goal.note||'메모 없음';actions.className='goal-actions';let scheduleButton=document.createElement('button');scheduleButton.textContent='공부 일정 추가';scheduleButton.onclick=()=>addScheduleFromGoal(goal);let editButton=document.createElement('button');editButton.textContent='수정';editButton.onclick=()=>openGoalEditor(goal,type);actions.append(scheduleButton,editButton);body.append(title,meta,actions);let more=document.createElement('button');more.className='goal-more';more.textContent='⋯';more.setAttribute('aria-label','목표 수정');more.onclick=()=>openGoalEditor(goal,type);card.append(check,body,more);list.append(card)})}
function renderMonth(){let title=$('#month-range'),calendar=$('#month-calendar'),detail=$('#month-detail'),key=monthKey(monthCursor),goals=periodGoals('month',key);title.textContent=new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long'}).format(monthCursor);$('#month-goals-panel').classList.toggle('hidden',monthMode!=='goals');$('#month-calendar-panel').classList.toggle('hidden',monthMode!=='calendar');$('#month-goal-summary').textContent=progressText(goals);renderGoalList($('#month-goal-list'),goals,'month');if(monthMode!=='calendar')return;calendar.innerHTML='';['월','화','수','목','금','토','일'].forEach(name=>{let h=document.createElement('div');h.className='month-weekday';h.textContent=name;calendar.append(h)});let first=new Date(monthCursor.getFullYear(),monthCursor.getMonth(),1),gridStart=startOfWeek(first);for(let i=0;i<42;i++){let date=addDays(gridStart,i),items=plansOn(date),button=document.createElement('button');button.className='month-day'+(date.getMonth()!==monthCursor.getMonth()?' muted':'')+(iso(date)===iso(new Date())?' today':'')+(iso(date)===iso(monthSelected)?' selected':'');button.innerHTML=`<span>${date.getDate()}</span>${items.length?`<span class="count">● ${items.length}</span>`:''}`;button.onclick=()=>{monthSelected=date;renderMonth()};calendar.append(button)}let items=plansOn(monthSelected).sort((a,b)=>minutes(a.start)-minutes(b.start));detail.innerHTML=`<h3>${formatDate(monthSelected)} 일정</h3>${items.length?items.map(item=>`<p>${item.start} – ${item.end} · ${item.title}</p>`).join(''):'<p class="empty">등록된 일정이 없어요.</p>'}`;let add=document.createElement('button');add.className='primary-button';add.textContent='이 날짜에 공부 계획 추가';add.onclick=()=>{selected=new Date(monthSelected);openEditor()};detail.append(add)}
function openGoalEditor(goal,type){let periodKey=type==='week'?weekKey(weekStart):monthKey(monthCursor);$('#goal-form').reset();$('#goal-id').value=goal?.id||'';$('#goal-type').value=type;$('#goal-editor-title').textContent=goal?'목표 수정':`${type==='week'?'주간':'월간'} 목표 추가`;$('#goal-subject').value=goal?.subject||'수학';$('#goal-title').value=goal?.title||'';$('#goal-note').value=goal?.note||'';$('#delete-goal-button').classList.toggle('hidden',!goal);$('#goal-sheet').dataset.periodKey=goal?.periodKey||periodKey;$('#sheet-backdrop').classList.remove('hidden');$('#goal-sheet').classList.remove('hidden');setTimeout(()=>$('#goal-title').focus(),50)}
function closeGoalEditor(){$('#goal-sheet').classList.add('hidden');$('#sheet-backdrop').classList.add('hidden')}
function addScheduleFromGoal(goal){pendingGoalLink=goal;selected=goal.periodKey.length===10?new Date(`${goal.periodKey}T00:00:00`):new Date(monthCursor);openEditor();$('#plan-title').value=`[목표 · ${goal.subject}] ${goal.title}`;$('#plan-goal-id').value=goal.id}
$('#goal-form').onsubmit=event=>{event.preventDefault();let type=$('#goal-type').value,id=$('#goal-id').value,collection=type==='week'?weekGoals:monthGoals,existing=collection.findIndex(goal=>goal.id===id),goal={id:id||crypto.randomUUID(),periodKey:$('#goal-sheet').dataset.periodKey,subject:$('#goal-subject').value,title:$('#goal-title').value.trim(),note:$('#goal-note').value.trim(),done:existing>=0?collection[existing].done:false};if(existing>=0)collection[existing]=goal;else collection.push(goal);persistGoals();closeGoalEditor()};
$('#delete-goal-button').onclick=()=>{let type=$('#goal-type').value,id=$('#goal-id').value;if(!confirm('이 목표를 삭제할까요? 연결된 공부 일정은 유지됩니다.'))return;if(type==='week')weekGoals=weekGoals.filter(goal=>goal.id!==id);else monthGoals=monthGoals.filter(goal=>goal.id!==id);plans=plans.map(plan=>plan.goalId===id?{...plan,goalId:null}:plan);save();persistGoals();closeGoalEditor()};
$('#close-goal-editor').onclick=closeGoalEditor;$('#add-week-goal').onclick=()=>openGoalEditor(null,'week');$('#add-month-goal').onclick=()=>openGoalEditor(null,'month');
document.querySelectorAll('[data-week-mode]').forEach(button=>button.onclick=()=>{weekMode=button.dataset.weekMode;document.querySelectorAll('[data-week-mode]').forEach(item=>item.classList.toggle('active',item===button));renderWeekGoals()});document.querySelectorAll('[data-month-mode]').forEach(button=>button.onclick=()=>{monthMode=button.dataset.monthMode;document.querySelectorAll('[data-month-mode]').forEach(item=>item.classList.toggle('active',item===button));renderMonth()});
$('#prev-week').onclick=()=>{weekStart=addDays(weekStart,-7);renderWeek();renderWeekGoals()};$('#next-week').onclick=()=>{weekStart=addDays(weekStart,7);renderWeek();renderWeekGoals()};$('#this-week-button').onclick=()=>{weekStart=startOfWeek(new Date());renderWeek();renderWeekGoals()};$('#prev-month').onclick=()=>{monthCursor=new Date(monthCursor.getFullYear(),monthCursor.getMonth()-1,1);renderMonth()};$('#next-month').onclick=()=>{monthCursor=new Date(monthCursor.getFullYear(),monthCursor.getMonth()+1,1);renderMonth()};$('#this-month-button').onclick=()=>{monthCursor=new Date();monthSelected=new Date();renderMonth()};
document.querySelectorAll('.nav-item').forEach(button=>button.onclick=()=>{document.querySelectorAll('.nav-item,.view').forEach(item=>item.classList.remove('active'));button.classList.add('active');$('#'+button.dataset.view).classList.add('active');$('#page-title').textContent=button.textContent.trim();if(button.dataset.view==='week-view'){renderWeek();renderWeekGoals()}if(button.dataset.view==='month-view')renderMonth()});
$('#sheet-backdrop').addEventListener('click',()=>{closeGoalEditor()});
$('#plan-form').addEventListener('submit',()=>{if(!pendingGoalLink)return;setTimeout(()=>{if(!$('#editor-sheet').classList.contains('hidden'))return;let title=$('#plan-title').value,date=$('#plan-date').value,start=$('#plan-start').value,end=$('#plan-end').value,plan=[...plans].reverse().find(item=>item.title===title&&item.date===date&&item.start===start&&item.end===end&&!item.goalId);if(plan){plan.goalId=pendingGoalLink.id;save()}pendingGoalLink=null},0)},true);
const originalExport=$('#export-button').onclick;$('#export-button').onclick=()=>{let payload={version:2,exportedAt:new Date().toISOString(),plans,weekGoals,monthGoals},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`study-planner-${iso(new Date())}.json`;link.click();URL.revokeObjectURL(link.href)};
const originalImport=$('#import-input').onchange;$('#import-input').onchange=async event=>{let file=event.target.files[0];if(!file)return;try{let data=JSON.parse(await file.text());if(!Array.isArray(data.plans)||('weekGoals'in data&&!Array.isArray(data.weekGoals))||('monthGoals'in data&&!Array.isArray(data.monthGoals)))throw Error();if(confirm(`일정 ${data.plans.length}개와 목표 데이터를 현재 데이터로 교체할까요?`)){plans=data.plans;weekGoals=Array.isArray(data.weekGoals)?data.weekGoals:[];monthGoals=Array.isArray(data.monthGoals)?data.monthGoals:[];save();persistGoals();alert('가져왔어요.')}}catch{alert('스터디 플래너에서 내보낸 올바른 JSON 파일인지 확인해 주세요.')}finally{event.target.value=''}};
renderGoalAreas();
